CREATE TABLE APPOINTMENT
(
  APPOINTMENT_ID INT NOT NULL,
  DATE INT NOT NULL,
  TIME INT NOT NULL,
  STATUS INT NOT NULL,
  PRIMARY KEY (APPOINTMENT_ID)
);

CREATE TABLE PRESCRIPTION
(
  PRESCRIPTION_ID INT NOT NULL,
  DATE INT NOT NULL,
  PRIMARY KEY (PRESCRIPTION_ID)
);

CREATE TABLE BILLING
(
  BILL_ID INT NOT NULL,
  BILL_DATE INT NOT NULL,
  AMOUNT INT NOT NULL,
  PAYEMNT_STATUS INT NOT NULL,
  PRIMARY KEY (BILL_ID)
);

CREATE TABLE PATIENT
(
  PATEINT_ID INT NOT NULL,
  NAME INT NOT NULL,
  AGE INT NOT NULL,
  GENDER INT NOT NULL,
  ADDRESS INT NOT NULL,
  PHONE INT NOT NULL,
  APPOINTMENT_ID INT NOT NULL,
  PRESCRIPTION_ID INT NOT NULL,
  BILL_ID INT NOT NULL,
  PRIMARY KEY (PATEINT_ID),
  FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID),
  FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPTION(PRESCRIPTION_ID),
  FOREIGN KEY (BILL_ID) REFERENCES BILLING(BILL_ID)
);

CREATE TABLE DOCTOR
(
  DOCTOR_ID INT NOT NULL,
  NAME INT NOT NULL,
  SPECIALIZATION INT NOT NULL,
  CONTACT_NUMBER INT NOT NULL,
  APPOINTMENT_ID INT NOT NULL,
  PRESCRIPTION_ID INT NOT NULL,
  PRIMARY KEY (DOCTOR_ID),
  FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID),
  FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPTION(PRESCRIPTION_ID)
);

CREATE TABLE MEDICINE
(
  MEDICINE_ID INT NOT NULL,
  NAME INT NOT NULL,
  PRICE INT NOT NULL,
  STOCK_QUANTITY INT NOT NULL,
  PRIMARY KEY (MEDICINE_ID)
);

CREATE TABLE DEPARTMENT
(
  DEPARTMENT_ID INT NOT NULL,
  DEPARTMENT_NAME INT NOT NULL,
  LOCATION INT NOT NULL,
  DOCTOR_ID INT NOT NULL,
  PRIMARY KEY (DEPARTMENT_ID),
  FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)
);

CREATE TABLE CONTAINS
(
  PRESCRIPTION_ID INT NOT NULL,
  MEDICINE_ID INT NOT NULL,
  PRIMARY KEY (PRESCRIPTION_ID, MEDICINE_ID),
  FOREIGN KEY (PRESCRIPTION_ID) REFERENCES PRESCRIPTION(PRESCRIPTION_ID),
  FOREIGN KEY (MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID)
);